version: 2
registries:
  wex-github:
    type: git
    url: https://github.com
    token: ${{secrets.WEX_GITHUB_TOKEN}}
updates:
- package-ecosystem: bundler
  directory: "/"
  insecure-external-code-execution: allow
  registries:
  - wex-github
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
