---
send_first_email_reminder:
  active: <%= ENV["FEATURE_TOGGLE_SEND_FIRST_EMAIL_REMINDER"] || "true" %>
send_second_email_reminder:
  active: <%= ENV["FEATURE_TOGGLE_SEND_SECOND_EMAIL_REMINDER"] || "true" %>
send_final_text_reminder:
  active: <%= ENV["FEATURE_TOGGLE_SEND_FINAL_TEXT_REMINDER"] || "true" %>
enable_renewals:
  active: <%= ENV["FEATURE_TOGGLE_ENABLE_RENEWALS"] || "false" %>
generate_boxi_report:
  active: true
